[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "dialogue"
version = "1.0.0"
authors = [
  {name="Eric", email="eric@locallyringed.space"}
]
description = "An engine and library for handling dialogue graphs in video games."
readme = "README.md"
license = "LGPL-2.1-or-later"
license-files = ["LICENSE"]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Games/Entertainment",
    "Topic :: Software Development :: Libraries",
]
dependencies = [
  "dash>=4.4.0",
  "dash-cytoscape>=1.0.2",
  "graphviz>=0.21",
  "PyYAML>=6.0.3",
]

[project.optional-dependencies]
dev = [
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "pytest-testmon>=2.2.0",
  "pytest-xdist>=3.8.0",
]

[project.urls]
Homepage = "https://github.com/Cnecomicz/dialogue"
Issues = "https://github.com/Cnecomicz/dialogue/issues"

[project.scripts]
dialogue-editor = "dash_app.app:main"
dialogue-render = "dialogue_viewer.graph_viewer:main"
dialogue-validate = "dialogue_validator.graph_validator:main"

[tool.hatch.build.targets.wheel]
packages = [
  "src/dash_app",
  "src/dialogue_editor",
  "src/dialogue_model",
  "src/dialogue_navigator",
  "src/dialogue_validator",
  "src/dialogue_viewer",
]
