[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dialogue"
version = "0.9"
authors = [
  {name="Eric", email="eric@locallyringed.space"}
]
description = "An engine and library for handling dialogue graphs in video games."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "dash", 
  "dash-cytoscape", 
  "graphviz", 
  "PyYAML",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "pytest-testmon",
  "pytest-xdist",
]

[project.urls]
Homepage = "https://github.com/Cnecomicz/dialogue"
Issues = "https://github.com/Cnecomicz/dialogue/issues"

[project.scripts]
dialogue-editor = "dash_app.app:main"
render = "dialogue_viewer.graph_viewer:main"

[tool.hatch.build.targets.wheel]
packages = [
  "src/dash_app",
  "src/dialogue_editor",
  "src/dialogue_model",
  "src/dialogue_navigator",
  "src/dialogue_viewer",
]
